In [1]:
print("Hello World")

Hello World

In [4]:
import pandas as pd

In [27]:
data = pd.read_csv("Data/03_Library Systembook.csv")

In [28]:
data

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
...,...,...,...,...,...,...
109,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
data = data.fillna("value", inplace=True)

In [29]:
data.dtypes

Id                        float64
Books                      object
Book checkout              object
Book Returned              object
Days allowed to borrow     object
Customer ID               float64
dtype: object

In [30]:
data

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
...,...,...,...,...,...,...
109,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
data_cleaned = data.dropna(how="all")

In [43]:
data_cleaned

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0
20,21.0,NaN,"""01/06/2023""",05/06/2023,2 weeks,NaN

In [33]:
data_cleaned

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0
20,21.0,NaN,"""01/06/2023""",05/06/2023,2 weeks,NaN

In [45]:
data_cleaned2 = pd.to_datetime(data["Book checkout"],  format='%d/%m/%Y')

ValueError: time data ""20/02/2023"" doesn't match format "%d/%m/%Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [35]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
109     True
110     True
111     True
112     True
113     True
Length: 114, dtype: bool